ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
    
    # 输入1：下位机轮速里程计（从 /get_vel 积分得到）
    odom0: /wheel_odom
    odom0_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]
    
    # 输入2：雷达里程计
    odom1: /laser_odom
    odom1_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]


    # 轮式里程计的协方差（角度漂移较大）
    odom0_pose_covariance: [0.01, 0.0, 0.0,
                                0.0, 0.01, 0.0,
                                0.0, 0.0, 0.01]
    odom0_twist_covariance: [0.001, 0.0, 0.0,
                                  0.0, 0.001, 0.0,
                                  0.0, 0.0, 0.05]  # 角度漂移大

    # 激光里程计的协方差（更准确）
    odom1_pose_covariance: [0.05, 0.0, 0.0,
                                0.0, 0.05, 0.0,
                                0.0, 0.0, 0.05]
    odom1_twist_covariance: [0.01, 0.0, 0.0,
                                  0.0, 0.01, 0.0,
                                  0.0, 0.0, 0.01]